# Generated by Django 4.2.16 on 2024-12-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='Age',
        ),
    ]
