# Generated by Django 4.2.16 on 2024-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FB', '0002_remove_models_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='id',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
