# Generated by Django 4.2.16 on 2024-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FB', '0003_alter_models_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='phone',
            field=models.IntegerField(default=True),
        ),
    ]
